### ISSUE TITLE
everware can't launch kernel

### ISSUE THREAD

**Issue by betatim** [everware/everware-dimuon-example#1]
With the latest changes using this repo on everware.rep.school.yandex.net doesn't work. The jupyterhub list of files comes up but if you try and start a notebook it fails because it can't connect to the kernel.

From the last few commits it looks like we changed the base image, which one of the files in `yandex/rep` are the ones that were used to make the image. Neither contain the infamous `singleuser.sh` I was looking for :-/

cc @anaderi

**Comment by betatim** [comment]
I launched revision 9bec6770485eb6b245648bc251d045a204973cc9 with the everware-beta instance at CERN and there it works. Mysterious ...

Maybe `docker logs -f ...` on the yandex instance can give us some hints

**Comment by anaderi** [comment]
was a proxy misconfiguration. fixed.

**Comment by betatim** [comment]
Nice. Can you explain a bit why the dimuon example didn't work but the
cern-demo one did? This was what really confused me.

**Comment by anaderi** [comment]
that's strange. the problem was that Jupyter uses 2 connections (one for http and another for websocket) and proxy was configured to pass only http.

**Comment by betatim** [comment]
Weird indeed.
